[conf]
default-lang = "eng"

[lang.eng]
date = "Date"
exercise = "Exercise"
lesson = "Lesson"
table-of-contents = "Table of contents"
version = "Version"

[lang.pol]
date = "Data"
exercise = "Ćwiczenie"
lesson = "Lekcja"
table-of-contents = "Spis treści"
version = "Wersja"
