[package]
name = "dpurge-langnote"
version = "0.0.1"
description = "Language learning notebook"
authors = ["D. Purge <https://github.com/dpurge>"]
repository = "https://github.com/dpurge/typst-lib"
entrypoint = "lib.typ"
exclude = []
compiler = "0.12.0"
license = "MIT"
categories = ["notebook"]
keywords = ["language", "notebook"]